"""
Builds "Pass Rush Generation Index" -- claude_code_spec_ol_vs_pass_rush_matchup.md's "new
piece." Pass Defense Matchup already carries three real pass-rush-adjacent columns (Sack
Rate, Pressure Proxy [QB Hit Rate], Blitz Rate) as REFERENCED, context-only columns -- they
were never combined into their own composite anywhere in this workbook. This tab builds that
composite: a real, team-level "Pass Rush Generation Score," Z-scored (not converted to a
points-scale Score the way every other tab's Section 5 is) because it exists specifically to
be subtracted from Offensive Line Index's own Pass Protection Z-score in the OL vs. Pass Rush
Matchup wiring (see build_ol_pass_rush_wiring.py) -- a raw Z-score difference, not two
points-scale Section-5 Scores subtracted the way Pass/Run Matchup Differential already work.

NO NEW DATA PULL: every real number on this tab is a live formula reference to Pass Defense
Matchup's own Section 1 (Sack Rate/Pressure Proxy/Blitz Rate, columns H/I/J), which is itself
already a live reference to Front Seven Index's real Section 1 data. Team/Season labels are
ALSO referenced (not independently regenerated), so a positional row mismatch between this
tab and Pass Defense Matchup is structurally impossible -- if the two tabs' rows ever drifted
apart, the Team/Season labels themselves would visibly show it, not silently misalign data.
This is why the Section 1 formulas below use a direct same-row reference (this tab's row 5
reads Pass Defense Matchup's row 5, etc.) rather than a SUMPRODUCT-array MATCH -- both tabs
are built from the identical TEAM_ORDER x HISTORICAL_YEARS construction, sorted identically,
so a positional reference is exact and simpler than a lookup.

Same 5-section decay-weighted shape as Pass Defense Matchup / Run Defense Matchup (team-
level, no rookie concept, no Section 2B, no individual-player Section 6, NO Team Ratings
wiring -- this is a matchup-support composite, not a static team-quality number, same
architectural category as Pass/Run Defense Matchup).

Sack Rate / Pressure Proxy (QB Hit Rate) / Blitz Rate are all real "generated BY the
defense" rates (not "allowed" rates), same orientation Front Seven Index's own composite
already uses for these two -- higher is better pass-rush generation, no sign-flip needed
for any of the three.

NOT YET VALIDATED: same disclaimer as every tab in the Defensive Matchup Engine family --
no backtesting harness exists yet to prove this composite (or the matchup it feeds) actually
improves predictions.

Usage:
    uv run python scripts/build_pass_rush_generation_index.py \\
        "C:\\path\\to\\NFL_Prediction_Model.xlsx"
"""
from __future__ import annotations

import sys
from pathlib import Path

import openpyxl
from openpyxl.styles import Alignment, Font, PatternFill
from openpyxl.utils import get_column_letter

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "src"))

HISTORICAL_YEARS = [2023, 2024, 2025]
SHEET_NAME = "Pass Rush Generation Index"
PASS_DEFENSE_SHEET = "Pass Defense Matchup"
RUN_DEFENSE_SHEET = "Run Defense Matchup"

# Pass Defense Matchup's own real Section 1 range (verified against that tab's own build
# script: sec1_first_row=5, 32 teams x 3 years = 96 rows). Team/Season = A/B, referenced
# columns Sack Rate/Pressure Proxy/Blitz Rate = H/I/J.
PASS_DEF_SEC1_FIRST_ROW = 5
PASS_DEF_SEC1_LAST_ROW = 100
PASS_DEF_COLS = {"sack": "H", "pressure": "I", "blitz": "J"}

METRICS = [
    {"key": "sack", "label": "Sack Rate\n(ref)", "fmt": "0.00%"},
    {"key": "pressure", "label": "Pressure Proxy\n(QB Hit Rate, ref)", "fmt": "0.00%"},
    {"key": "blitz", "label": "Blitz Rate\n(ref)", "fmt": "0.00%"},
]

TEAM_ORDER = [
    "Buffalo Bills", "Miami Dolphins", "New England Patriots", "New York Jets",
    "Baltimore Ravens", "Cincinnati Bengals", "Cleveland Browns", "Pittsburgh Steelers",
    "Houston Texans", "Indianapolis Colts", "Jacksonville Jaguars", "Tennessee Titans",
    "Denver Broncos", "Kansas City Chiefs", "Las Vegas Raiders", "Los Angeles Chargers",
    "Dallas Cowboys", "New York Giants", "Philadelphia Eagles", "Washington Commanders",
    "Chicago Bears", "Detroit Lions", "Green Bay Packers", "Minnesota Vikings",
    "Atlanta Falcons", "Carolina Panthers", "New Orleans Saints", "Tampa Bay Buccaneers",
    "Arizona Cardinals", "Los Angeles Rams", "San Francisco 49ers", "Seattle Seahawks",
]

TITLE_FONT = Font(name="Arial", size=10, bold=True)
TITLE_FILL = PatternFill("solid", fgColor="FFD9E1F2")
HEADER_FONT = Font(name="Arial", size=10, bold=True, color="FFFFFFFF")
HEADER_FILL = PatternFill("solid", fgColor="FF1F4E78")
HEADER_ALIGN = Alignment(wrap_text=True, horizontal="center", vertical="center")
FORMULA_FONT = Font(name="Arial", size=10, color="FF000000")
LINK_FONT = Font(name="Arial", size=10, color="FF008000")
NOTE_FONT = Font(name="Arial", size=9, color="FF808080")
ASSUMPTION_FILL = PatternFill("solid", fgColor="FFFFFF00")
INPUT_FONT = Font(name="Arial", size=10, color="FF0000FF")


def _section_title(ws, row: int, last_col: int, text: str) -> None:
    ws.merge_cells(start_row=row, start_column=1, end_row=row, end_column=last_col)
    cell = ws.cell(row=row, column=1, value=text)
    cell.font = TITLE_FONT
    cell.fill = TITLE_FILL


def _header_row(ws, row: int, headers: list[str], height: float = 28) -> None:
    ws.row_dimensions[row].height = height
    for col, text in enumerate(headers, start=1):
        cell = ws.cell(row=row, column=col, value=text)
        cell.font = HEADER_FONT
        cell.fill = HEADER_FILL
        cell.alignment = HEADER_ALIGN


def add_model_assumptions_weights(wb: openpyxl.Workbook) -> None:
    ws = wb["Model Assumptions"]
    title_row = 118
    ws.merge_cells(f"A{title_row}:D{title_row}")
    title = ws.cell(row=title_row, column=1, value=(
        "Pass Rush Generation Index Weighting (Z-score composite -- NO points-scale "
        "conversion; feeds the OL vs. Pass Rush Matchup wiring directly in Z-units -- see "
        "'Pass Rush Generation Index' tab)"
    ))
    title.font = HEADER_FONT
    title.fill = HEADER_FILL

    rows = [
        (119, "Sack Rate Weight (Pass Rush Generation Index)", 0.5,
         "The most direct real outcome of a real pass rush -- weighted highest."),
        (120, "Pressure Proxy Weight (QB Hit Rate, Pass Rush Generation Index)", 0.35,
         "Real pressure that didn't finish as a sack -- a real, direct pass-rush "
         "outcome, weighted second (same 'Pressure Proxy' framing/caveat Pass "
         "Defense Matchup's own reference column already carries)."),
        (121, "Blitz Rate Weight (Pass Rush Generation Index)", 0.15,
         "A real scheme-aggression signal, not a direct outcome the way Sack Rate/"
         "QB Hit Rate are -- a blitz-heavy defense generates more pressure LOOKS "
         "even when it doesn't convert, but this is a weaker, more indirect real "
         "signal than the other two, so it's weighted lowest."),
    ]
    for row, label, value, note in rows:
        ws.cell(row=row, column=2, value=label)
        c = ws.cell(row=row, column=3, value=value)
        c.font = INPUT_FONT
        c.fill = ASSUMPTION_FILL
        c.number_format = "0.00"
        n = ws.cell(row=row, column=4, value=note)
        n.font = NOTE_FONT
        n.alignment = Alignment(wrap_text=True, vertical="top")


def build(workbook_path: str) -> dict:
    wb = openpyxl.load_workbook(workbook_path)
    if PASS_DEFENSE_SHEET not in wb.sheetnames:
        raise ValueError(
            f"'{PASS_DEFENSE_SHEET}' not found -- run build_pass_defense_matchup.py first "
            "(this tab references its Section 1 directly, no new data pull of its own)."
        )

    add_model_assumptions_weights(wb)

    if SHEET_NAME in wb.sheetnames:
        del wb[SHEET_NAME]
    for candidate in (RUN_DEFENSE_SHEET, PASS_DEFENSE_SHEET):
        if candidate in wb.sheetnames:
            insert_after = candidate
            break
    else:
        insert_after = wb.sheetnames[0]
    ws = wb.create_sheet(SHEET_NAME, index=wb.sheetnames.index(insert_after) + 1)
    ws.column_dimensions["A"].width = 20.0
    ws.column_dimensions["C"].width = 20.0

    ws.merge_cells("A1:H1")
    t = ws.cell(row=1, column=1, value=(
        "Pass Rush Generation Index -- claude_code_spec_ol_vs_pass_rush_matchup.md. Real, "
        "team-level Sack Rate / Pressure Proxy (QB Hit Rate) / Blitz Rate, LIVE-REFERENCED "
        "from Pass Defense Matchup (itself referenced from Front Seven Index) -- NO new "
        "data pull. Combined here into a Z-scored 'Pass Rush Generation Score' that feeds "
        "the OL vs. Pass Rush Matchup wiring on Week 1 Matchups. NOT YET VALIDATED against "
        "real outcomes -- see the closing note."
    ))
    t.font = Font(name="Arial", size=12, bold=True)

    # ==== Section 1: Raw 3-year TEAM-level data, 100% live-referenced (no new data pull) ===
    sec1_first_row = 5
    sec1_last_row = sec1_first_row + (PASS_DEF_SEC1_LAST_ROW - PASS_DEF_SEC1_FIRST_ROW)
    _section_title(
        ws, 3, 5,
        "Section 1 — Raw 3-Year TEAM-Level Data, 100% LIVE-REFERENCED from Pass Defense "
        "Matchup's own Section 1 (Sack Rate/Pressure Proxy/Blitz Rate, cols H/I/J) -- "
        "Team/Season are referenced too, so this tab's rows can never silently misalign "
        "with its source (see this tab's opening note). NO new data pull.",
    )
    _header_row(ws, 4, ["Team", "Season", *[m["label"] for m in METRICS]])

    for i in range(sec1_last_row - sec1_first_row + 1):
        row = sec1_first_row + i
        src_row = PASS_DEF_SEC1_FIRST_ROW + i
        team_f = ws.cell(row=row, column=1, value=f"='{PASS_DEFENSE_SHEET}'!A{src_row}")
        season_f = ws.cell(row=row, column=2, value=f"='{PASS_DEFENSE_SHEET}'!B{src_row}")
        team_f.font = LINK_FONT
        season_f.font = LINK_FONT
        for j, m in enumerate(METRICS):
            col = 3 + j
            src_col = PASS_DEF_COLS[m["key"]]
            cell = ws.cell(
                row=row, column=col,
                value=f"='{PASS_DEFENSE_SHEET}'!{src_col}{src_row}",
            )
            cell.font = LINK_FONT
            cell.number_format = m["fmt"]

    team_range = f"$A${sec1_first_row}:$A${sec1_last_row}"
    season_range = f"$B${sec1_first_row}:$B${sec1_last_row}"
    sec1_col_of = {m["key"]: get_column_letter(3 + j) for j, m in enumerate(METRICS)}
    metric_ranges = {
        m["key"]: (
            f"${sec1_col_of[m['key']]}${sec1_first_row}:${sec1_col_of[m['key']]}${sec1_last_row}"
        )
        for m in METRICS
    }

    # ==== Section 2: League average per season ==============================================
    sec2_title_row = sec1_last_row + 2
    sec2_header_row = sec2_title_row + 1
    season_rows = {yr: sec2_header_row + 1 + i for i, yr in enumerate(HISTORICAL_YEARS)}

    _section_title(
        ws, sec2_title_row, 4,
        "Section 2 — League Average per Season (simple average across all 32 teams)",
    )
    _header_row(ws, sec2_header_row, ["Season", *[m["label"] for m in METRICS]], height=20)

    for yr in HISTORICAL_YEARS:
        row = season_rows[yr]
        c = ws.cell(row=row, column=1, value=yr)
        c.font = INPUT_FONT
        for j, m in enumerate(METRICS):
            formula = f"=AVERAGEIF({season_range},{yr},{metric_ranges[m['key']]})"
            cell = ws.cell(row=row, column=2 + j, value=formula)
            cell.font = FORMULA_FONT
            cell.number_format = m["fmt"]

    season_avg_col = {m["key"]: get_column_letter(2 + j) for j, m in enumerate(METRICS)}

    # ==== Section 3: Per-team decay-weighted, regressed baseline ===========================
    sec3_title_row = season_rows[HISTORICAL_YEARS[-1]] + 2
    sec3_header_row = sec3_title_row + 1
    sec3_first_row = sec3_header_row + 1
    n_teams = len(TEAM_ORDER)
    sec3_last_row = sec3_first_row + n_teams - 1
    sec3_last_col = 2 + len(METRICS) * 7

    _section_title(
        ws, sec3_title_row, sec3_last_col,
        "Section 3 — Per-Team 3-Yr Decay-Weighted, Regressed Baseline. A missing year "
        "substitutes THAT season's own Section 2 league average (no rookie concept for a "
        "team-level stat).",
    )
    headers = ["Team", "Years of\nReal History"]
    metric_block_start_col: dict[str, int] = {}
    col_cursor = 3
    for m in METRICS:
        metric_block_start_col[m["key"]] = col_cursor
        headers += [
            f"{m['label']} Y-1", f"{m['label']} Y-2", f"{m['label']} Y-3",
            f"Weighted\n{m['label']} Avg\n(3-Yr decay)", f"Team History\n{m['label']}",
            f"League Baseline\n{m['label']} (Y-1)", f"Projected 3-Yr\n{m['label']} Baseline",
        ]
        col_cursor += 7
    _header_row(ws, sec3_header_row, headers)

    for i, team in enumerate(TEAM_ORDER):
        row = sec3_first_row + i
        ws.cell(row=row, column=1, value=team).font = FORMULA_FONT

        years_hist_terms = "+".join(
            f"--(COUNTIFS({team_range},$A{row},{season_range},'Model Assumptions'!$C$18-{k})>0)"
            for k in (1, 2, 3)
        )
        yh = ws.cell(row=row, column=2, value=f"={years_hist_terms}")
        yh.font = FORMULA_FONT
        yh.number_format = "0"

        for m in METRICS:
            base = metric_block_start_col[m["key"]]
            y1, y2, y3, wavg, th, lb, pb = (get_column_letter(base + k) for k in range(7))
            mrange = metric_ranges[m["key"]]
            sec2_col = season_avg_col[m["key"]]

            def _ysub(offset: int, mrange=mrange, sec2_col=sec2_col) -> str:
                season_avg_lookup = (
                    f"INDEX(${sec2_col}${season_rows[HISTORICAL_YEARS[0]]}:"
                    f"${sec2_col}${season_rows[HISTORICAL_YEARS[-1]]},"
                    f"MATCH('Model Assumptions'!$C$18-{offset},"
                    f"$A${season_rows[HISTORICAL_YEARS[0]]}:"
                    f"$A${season_rows[HISTORICAL_YEARS[-1]]},0))"
                )
                return (
                    f"=IF(COUNTIFS({team_range},$A{row},{season_range},"
                    f"'Model Assumptions'!$C$18-{offset})=0,{season_avg_lookup},"
                    f"SUMIFS({mrange},{team_range},$A{row},{season_range},"
                    f"'Model Assumptions'!$C$18-{offset}))"
                )

            f_y1 = ws.cell(row=row, column=base, value=_ysub(1))
            f_y2 = ws.cell(row=row, column=base + 1, value=_ysub(2))
            f_y3 = ws.cell(row=row, column=base + 2, value=_ysub(3))
            f_wavg = ws.cell(row=row, column=base + 3, value=(
                f"=({y1}{row}*1+{y2}{row}*'Model Assumptions'!$C$20+"
                f"{y3}{row}*('Model Assumptions'!$C$20^2))/"
                f"(1+'Model Assumptions'!$C$20+'Model Assumptions'!$C$20^2)"
            ))
            f_th = ws.cell(row=row, column=base + 4, value=(
                f"={y1}{row}*'Model Assumptions'!$C$22+{wavg}{row}*(1-'Model Assumptions'!$C$22)"
            ))
            f_lb = ws.cell(row=row, column=base + 5, value=(
                f"=INDEX(${sec2_col}${season_rows[HISTORICAL_YEARS[0]]}:"
                f"${sec2_col}${season_rows[HISTORICAL_YEARS[-1]]},"
                f"MATCH('Model Assumptions'!$C$18-1,$A${season_rows[HISTORICAL_YEARS[0]]}:"
                f"$A${season_rows[HISTORICAL_YEARS[-1]]},0))"
            ))
            f_pb = ws.cell(row=row, column=base + 6, value=(
                f"={th}{row}*'Model Assumptions'!$C$21+{lb}{row}*(1-'Model Assumptions'!$C$21)"
            ))
            for cell in (f_y1, f_y2, f_y3, f_wavg, f_th, f_lb, f_pb):
                cell.font = FORMULA_FONT
                cell.number_format = m["fmt"]

    # ==== Section 4: League average/std-dev of Section 3's Projected Baselines =============
    sec4_title_row = sec3_last_row + 2
    sec4_header_row = sec4_title_row + 1
    avg_row, std_row = sec4_header_row + 1, sec4_header_row + 2

    _section_title(
        ws, sec4_title_row, 4, "Section 4 — League Average & Std. Dev. of the 3-Yr Baselines"
    )
    _header_row(ws, sec4_header_row, ["Stat", *[m["label"] for m in METRICS]], height=18)

    ws.cell(row=avg_row, column=1, value="League Average").font = FORMULA_FONT
    ws.cell(row=std_row, column=1, value="League Std. Dev.").font = FORMULA_FONT

    proj_baseline_col = {
        m["key"]: get_column_letter(metric_block_start_col[m["key"]] + 6) for m in METRICS
    }
    for j, m in enumerate(METRICS):
        pcol = proj_baseline_col[m["key"]]
        pb_range = f"{pcol}${sec3_first_row}:{pcol}${sec3_last_row}"
        a = ws.cell(row=avg_row, column=2 + j, value=f"=AVERAGE({pb_range})")
        s = ws.cell(row=std_row, column=2 + j, value=f"=STDEVP({pb_range})")
        for cell in (a, s):
            cell.font = FORMULA_FONT
            cell.number_format = m["fmt"]

    # ==== Section 5: Z-scores + Pass Rush Generation Score (Z) -- NO points-scale column ====
    sec5_title_row = std_row + 2
    sec5_header_row = sec5_title_row + 1
    sec5_first_row = sec5_header_row + 1
    sec5_last_row = sec5_first_row + n_teams - 1

    _section_title(
        ws, sec5_title_row, 6,
        "Section 5 — Z-Scores and Pass Rush Generation Score. All three metrics are real "
        "rates GENERATED BY the defense (not \"allowed\" rates) -- higher is better pass-"
        "rush generation, no sign-flip needed for any of the three, same orientation Front "
        "Seven Index's own composite already uses. DELIBERATELY NO points-scale column "
        "here (unlike every other Section 5 in this workbook) -- the Weighted Z-Score Sum "
        "IS the 'Pass Rush Generation Score (Z)' the OL vs. Pass Rush Matchup wiring "
        "subtracts directly against Offensive Line Index's own Pass Protection Z.",
    )
    _header_row(
        ws, sec5_header_row,
        ["Team", *[f"{m['label']}\nZ" for m in METRICS],
         "Pass Rush Generation\nScore (Z)", "Years of\nReal History"],
    )

    avg_cell_ref = {
        m["key"]: f"${get_column_letter(2 + j)}${avg_row}" for j, m in enumerate(METRICS)
    }
    std_cell_ref = {
        m["key"]: f"${get_column_letter(2 + j)}${std_row}" for j, m in enumerate(METRICS)
    }
    weight_cells = {"sack": "$C$119", "pressure": "$C$120", "blitz": "$C$121"}

    for i in range(n_teams):
        sec3_row = sec3_first_row + i
        row = sec5_first_row + i
        f = ws.cell(row=row, column=1, value=f"=A{sec3_row}")
        f.font = FORMULA_FONT

        z_cols = []
        for j, m in enumerate(METRICS):
            pcol = proj_baseline_col[m["key"]]
            formula = f"=({pcol}{sec3_row}-{avg_cell_ref[m['key']]})/{std_cell_ref[m['key']]}"
            col = 2 + j
            cell = ws.cell(row=row, column=col, value=formula)
            cell.font = FORMULA_FONT
            cell.number_format = "0.00"
            z_cols.append(get_column_letter(col))

        weighted_terms = " + ".join(
            f"{z_cols[j]}{row}*'Model Assumptions'!{weight_cells[m['key']]}"
            for j, m in enumerate(METRICS)
        )
        wz_col = 2 + len(METRICS)
        wz = ws.cell(row=row, column=wz_col, value=f"={weighted_terms}")
        wz.font = FORMULA_FONT
        wz.number_format = "0.00"

        yh_link = ws.cell(row=row, column=wz_col + 1, value=f"=B{sec3_row}")
        yh_link.font = FORMULA_FONT
        yh_link.number_format = "0"

    # ---- Closing note --------------------------------------------------------------------
    note_row = sec5_last_row + 2
    ws.merge_cells(start_row=note_row, start_column=1, end_row=note_row, end_column=8)
    note = ws.cell(row=note_row, column=1, value=(
        "claude_code_spec_ol_vs_pass_rush_matchup.md. NOT YET VALIDATED: no backtesting "
        "harness exists yet to prove this composite (or the OL vs. Pass Rush Matchup it "
        "feeds) improves predictions -- this is real, verified-correct plumbing, not a "
        "proven improvement. Every real number on this tab is a LIVE reference (Section 1, "
        "green) to Pass Defense Matchup's own Section 1 (Sack Rate/Pressure Proxy/Blitz "
        "Rate), which is itself a live reference to Front Seven Index's real data -- NO new "
        "data pull, nothing recomputed. Team/Season are referenced too (not independently "
        "regenerated), so a row-alignment mismatch between this tab and its source is "
        "structurally impossible. Section 5 deliberately has NO points-scale 'Score' column "
        "-- the Weighted Z-Score Sum itself IS the Pass Rush Generation Score (Z) that the "
        "OL vs. Pass Rush Matchup wiring (Week 1 Matchups) subtracts directly against "
        "Offensive Line Index's own real Pass Protection Z (Section 5, col B there) -- see "
        "build_ol_pass_rush_wiring.py. This tab has NO Team Ratings wiring, same reasoning "
        "as Pass/Run Defense Matchup: it's a matchup-support composite, not a static team-"
        "quality number."
    ))
    note.font = NOTE_FONT
    note.alignment = Alignment(wrap_text=True, vertical="top")

    wb.save(workbook_path)
    print(
        f"Built '{SHEET_NAME}': Section 1 {sec1_last_row - sec1_first_row + 1} rows "
        f"(100% referenced, no new data pull), Section 3/5 {n_teams} teams. NOT wired into "
        f"Team Ratings -- feeds the OL vs. Pass Rush Matchup wiring directly."
    )
    print(f"Saved to {workbook_path}")
    return {
        "n_teams": n_teams,
        "sec3_range": (sec3_first_row, sec3_last_row),
        "sec5_range": (sec5_first_row, sec5_last_row),
    }


if __name__ == "__main__":
    if len(sys.argv) != 2:
        print(
            'Usage: uv run python scripts/build_pass_rush_generation_index.py '
            '"path/to/workbook.xlsx"'
        )
        sys.exit(1)
    build(sys.argv[1])
